version: "3.8"

services:
  localstack:
    container_name: localstack_echoguard
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,lambda,cloudformation,sts,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
    volumes:
      - "./infra:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  init-aws:
    image: python:3.9-slim
    depends_on:
      localstack:
        condition: service_healthy 
    volumes:
      - ${PWD}:/app                         
      - /var/run/docker.sock:/var/run/docker.sock 
    working_dir: /app
    user: root 
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    command: >
          bash -c "
            echo 'ğŸ“‚ SPRAWDZANIE PLIKÃ“W W KONTENERZE:' &&
            ls -la /app &&
            ls -la /app/src || echo 'âŒ Brak katalogu SRC!' &&
            
            echo 'â³ Instalacja zaleÅ¼noÅ›ci...' &&
            apt-get update && apt-get install -y docker.io curl &&
            pip install boto3 &&
            
            echo 'ğŸš€ Uruchamianie deploymentu...' &&
            python build_and_deploy.py
          "